# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 19:03
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_markdown.models
import error_posts.models
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', django_markdown.models.MarkdownField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('exception_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField()),
                ('sanitized_traceback', models.TextField()),
                ('parsed_traceback', jsonfield.fields.JSONField()),
                ('raised_by', models.CharField(max_length=255)),
                ('raised_by_line', models.IntegerField()),
                ('django_version', models.CharField(choices=[('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9')], max_length=5)),
                ('how_to_reproduce', django_markdown.models.MarkdownField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=error_posts.models._generate_slug, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='error',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='error_posts.ErrorPost'),
        ),
        migrations.CreateModel(
            name='ErrorPostNonPublished',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('error_posts.errorpost',),
        ),
        migrations.CreateModel(
            name='ErrorPostPublished',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('error_posts.errorpost',),
        ),
    ]
