# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorpost',
            name='django_version',
            field=models.CharField(choices=[('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9'), ('1.10', '1.10')], max_length=5),
        ),
    ]
