# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_posts', '0002_auto_20170210_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorpost',
            name='data_came_from',
            field=models.CharField(choices=[('lib', 'Lib'), ('site', 'Site')], default='site', max_length=255),
            preserve_default=False,
        ),
    ]
