# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_posts', '0003_auto_20170815_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorpost',
            name='data_came_from',
            field=models.CharField(choices=[(b'lib', b'Lib'), (b'site', b'Site')], default='lib', max_length=255),
            preserve_default=False,
        ),
    ]
